### ISSUE TITLE
installation error with update to latest version

### ISSUE THREAD

**Issue by arp013** [zackwag/homebridge-somneo#11]
**Describe The Bug:**
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-somneo@latest

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-WSn4WLLJW0jSH52iG4PtHamSbU+hoxbuOPox87v1R8L/BgxdbXIDd9XUhir4OCR28kfZyTdwfHZxVAKdENhc5g== integrity checksum failed when using sha512: wanted sha512-WSn4WLLJW0jSH52iG4PtHamSbU+hoxbuOPox87v1R8L/BgxdbXIDd9XUhir4OCR28kfZyTdwfHZxVAKdENhc5g== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/homebridge-somneo: Integrity verification failed for sha512-WSn4WLLJW0jSH52iG4PtHamSbU+hoxbuOPox87v1R8L/BgxdbXIDd9XUhir4OCR28kfZyTdwfHZxVAKdENhc5g== (/home/pi/.npm/_cacache/content-v2/sha512/59/29/f858b2c95b48d21f9da21b83ed1da9926d4fa1a316ee38fa31f3bbf547c2ff060c5d6d720377d5d4862af8382476f247d9c937707c767154029d10d85ce6)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-03-17T18_30_43_285Z-debug.log

Command failed. Please review log for details.

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by zackwag** [comment]
Strange this seems like an error with NPM instead of the plugin.

In a post by oznu (one of the developers of Homebridge), linked to possible solutions:
https://www.reddit.com/r/homebridge/comments/j2jhdv/homebridge_116_cant_update_plugins/g75qzjp?utm_source=share&utm_medium=web2x&context=3

**Comment by arp013** [comment]
solved with 
npm cache clear --force
