### ISSUE TITLE
Correct spelling of "auxiliary"

### ISSUE THREAD

**Issue by khad** [zackwag/homebridge-somneo#21]
**Describe The Bug:**

Misspelling of "auxiliary".

**To Reproduce:**

First noticed in the UI, but there are some misspellings in the code as well.

**Expected behavior:**

Correct spelling. :)

**Screenshots:**

![Input sources](https://user-images.githubusercontent.com/758113/113941765-94b92080-97b4-11eb-8234-1300b9ab959b.PNG)

![auxilary](https://user-images.githubusercontent.com/758113/113942018-05603d00-97b5-11eb-8cc7-ca236ab6cd61.png)

**Comment by zackwag** [comment]
Thanks @khad! I've pushed up a PR -- https://github.com/zackwag/homebridge-somneo/pull/22
