### ISSUE TITLE
Config example of multiple Somneo lights

### ISSUE THREAD

**Issue by vvdheuvel** [zackwag/homebridge-somneo#29]
Could you share an example of a config with multiple Somneo lights? Thanks

**Comment by zackwag** [comment]
Do you mean multiple clocks? If so, `somneos` is an array, so you could do

```
{
  "name": "Homebridge Somneo",
  "somneos": [
    {
      "name": "First Somneo",
      "host": "[IP_ADDRESS_1]"
    },
    {
      "name": "Second Somneo",
      "host": "[IP_ADDRESS_2]"
    }
  ],
  "platform": "HomebridgeSomneo"
}
```
Where `IP_ADDRESS_1` is the first IP and `IP_ADDRESS_2` is the second IP.

I strongly suggest using the visual configuration plugin to set things up as it makes it much easier.

**Comment by vvdheuvel** [comment]
Actually I really meant multiple lights because Philips Somneo are Sleep & Wake-up Lights, with radio and clock functionality 😉 It works with my HOOBS set-up like a charm, thanks for the help!

**Comment by zackwag** [comment]
Ah! Ok. Awesome. Glad you got it working. Thanks for using the plug-in. I hope you enjoy it 😁

**Comment by vvdheuvel** [comment]
The kids love to operate their Somneo's with the Home app and it's a million miles better the Somneo Sensor plug-in 😋 keep up the good work!

**Comment by zackwag** [comment]
Thanks @vvdheuvel ! That's very kind of you to write. I really appreciate it 😄
