### ISSUE TITLE
Does the plugin work with " Philips Somneo HF3671/60"

### ISSUE THREAD

**Issue by ChalesGiron** [zackwag/homebridge-somneo#31]
**Is your feature request related to a problem? Please describe:**
Does the plugin work with " Philips Somneo HF367**1**/60"?

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

****

**Comment by zackwag** [comment]
I believe the HF3671/01 is an EU variant of the US device.

As long as the device uses the SleepMapper mobile app, this _should_ work with the plug-in. I can't say definitively as a I have only used the US device.

**Comment by ChalesGiron** [comment]
Great! Thanks for the response. I try to get my hands on the HF3671/01 and will send an update. It might take about two weeks. Ill ping you directly on another question.

**Comment by zackwag** [comment]
If you can confirm that it works, I'll update the README to include this model number as well 😄
